//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::answer::Entity as Answer;
pub use super::question::Entity as Question;
pub use super::quiz::Entity as Quiz;
pub use super::quiz_creation::Entity as QuizCreation;
