//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "quiz")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id:       Uuid,
	pub owner_id: i64,
	pub text:     String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::question::Entity")]
	Question,
	#[sea_orm(has_many = "super::quiz_creation::Entity")]
	QuizCreation,
}

impl Related<super::question::Entity> for Entity {
	fn to() -> RelationDef { Relation::Question.def() }
}

impl Related<super::quiz_creation::Entity> for Entity {
	fn to() -> RelationDef { Relation::QuizCreation.def() }
}

impl ActiveModelBehavior for ActiveModel {}
